### ISSUE TITLE
How can I generate a multi-view or 3D result by providing a prompt and a corresponding image?

### ISSUE THREAD

**Issue by 2019211753** [iSEE-Laboratory/DreamView#1]
Thank you for your amazing work and active contributions to open source. I'm very glad to receive your reply!

**Comment by yanjk3** [comment]
Thanks for your interest. But, actually our DreamView is a text-to-multi-view (3D) generation method and thus can't generate multi-view images or 3D under an image prompt. If you want to generate multi-view images or 3D with an image prompt, you'd better refer to SyncDreamer, Zero-1-to-3, etc. And if you want to generate any multi-view images with your text prompts, you can modify Line 113 - Line 118 [here](https://github.com/iSEE-Laboratory/DreamView/blob/main/DreamView-2D/t2i.py#L113), ways to generate 3D with text prompts will be updated later this month. Hope you have fun~~~~🥳🥳🥳

**Comment by 2019211753** [comment]
Thank you for your assistance. Your input was exactly what I needed.
