### ISSUE TITLE
Regarding the issue of quantitative indicators

### ISSUE THREAD

**Issue by chenyinlin1** [iSEE-Laboratory/DreamView#2]
Hello, this is a very interesting job.
May I ask if it is convenient to provide the code for calculating quantitative indicators? Thank you very much.

**Comment by yanjk3** [comment]
Unfortunately, that code is on my company PC, but I have done my internship. I remember that calculation is not complicated. For example, you can refer to [this code](https://github.com/iSEE-Laboratory/DreamView/blob/main/DreamView-2D/t2i.py) to get the generated images and then calculate the cos similarity with their corresponding text embeddings. For the calculation of the inception score, you can refer to [here](https://zhuanlan.zhihu.com/p/639410956). Hope the above are helpful.

**Comment by yanjk3** [comment]
I close this issue now, and if you encounter any other problems to calculating the quantitative indicators, plz reopen it.
