### ISSUE TITLE
The stable diffusion model file is missing

### ISSUE THREAD

**Issue by yangwenchengw** [iSEE-Laboratory/DreamView#3]
FileNotFoundError: Text embedding file .threestudio_cache/text_embeddings/a9b6c71b5fe715822ad3d0c99b7e8225.pt for model /mnt/data/.cache/huggingface/hub/models--stabilityai--stable-diffusion-2-1-base/ and prompt [An astronaut, riding a horse, wearing a white space suit, carrying a red backpack on the back] not found.

Can the missing documents be provided? Thank you so much

**Comment by yanjk3** [comment]
Actually if these text embeddings are not in your cache, they will be extracted automatically. So I need the output information of your issue to make sure what happens, plz paste them here : )

**Comment by yanjk3** [comment]
I close this issue now, and if you encounter any other problems, plz reopen it.
